### ISSUE TITLE
Counting not performing correctly

### ISSUE THREAD

**Issue by ollieeknight** [Zhen-Miao/PIC-snATAC#1]
Heya,

After running a command

`>   counts <- PIC_counting(colnames(libraries[[3]]), libraries[[3]]@assays$ATAC@fragments[[1]]@path, MACS2_peaks$combined)` I get the below error:
```R
|--------------------------------------------------|
|==================================================|
[1] "proportion of reads in cell barcdes is 0.662642773371796"
computing peak vector for each cell
Error in if (chunk_size > 1) { : missing value where TRUE/FALSE needed
In addition: Warning message:
In n_cells * n_features : NAs produced by integer overflow
```

this is my object:
```R
> libraries[[3]]
An object of class Seurat 
230230 features across 12416 samples within 1 assay 
Active assay: ATAC (230230 features, 0 variable features)
 2 layers present: counts, data
```

Do you have any suggestions as to things I could change? 

Thanks so much

Ollie

**Comment by Zhen-Miao** [comment]
Hi Ollie,

Thanks for bringing this up. This may be an issue with your `peak_set` input. We recommend using the GRanges object as input for `PIC_counting` function. If your input is a data.frame, could you please try this:

`peak_sets <- data_frame_to_GRanges(peak_sets)`

Let me know if this works! 

Best,
Zhen

**Comment by ollieeknight** [comment]
thanks, I appreciate your response! It worked well for two libraries before I ran this one, so i'm worried it's something with the fragment file, or cell names?

```R
>MACS2_peaks$combined
GRanges object with 194834 ranges and 0 metadata columns:
           seqnames            ranges strand
              <Rle>         <IRanges>  <Rle>
       [1]     chr1       10020-10473      *
       [2]     chr1     180736-181844      *
       [3]     chr1     191319-191739      *
       [4]     chr1     605390-605793      *
       [5]     chr1     778309-779299      *
       ...      ...               ...    ...
  [194830]     chrY 56829581-56829755      *
  [194831]     chrY 56831002-56831283      *
  [194832]     chrY 56831706-56831927      *
  [194833]     chrY 56834133-56834513      *
  [194834]     chrY 56836622-56837167      *
  -------
  seqinfo: 24 sequences from an unspecified genome; no seqlengths
```

**Comment by Zhen-Miao** [comment]
Thanks, I realize that this issue is due to integer overflow. It can be solved by adding `as.numeric()` function to convert integer into a floating point. I have updated the package and you can run the following code to install the current version. Hope this help sort things out! 

`devtools::install_github("Zhen-Miao/PICsnATAC", force = TRUE)`

Best,
Zhen

**Comment by ollieeknight** [comment]
great! that's worked perfectly. thank you!
